### ISSUE TITLE
Documentation read.me typo error

### ISSUE THREAD

**Issue by ocontant** [DNXLabs/terraform-aws-security-baseline#7]
### Contact Details (optional)

contant.olivier@gmail.com

### Description. What happened?

A bug happened!

Speficy / specify typo in read.me

### Steps to reproduce

Documentation typo error

Speficy

### Expected behavior

Specify

### Actual behavior

Speficy

### Occurrence

Frequently

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lzrocha** [comment]
Doc updated. Thanks!
